base_url = 'http://gohugo.io/'
languageCode = 'en-us'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 0
    url = "blog"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
author = "xorraxrax"
user = "lenartlola"
hostname = "github.io"
footerHTML = "<p>© 2023 <a href=>Lenart</a></p>"

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "github"
url = "https://github.com/lenartlola"

[[params.social]]
key = 1
name = "twitter"
url = "https://twitter.com/xorr0r0"

[[params.social]]
key = 3
name = "email"
url = "mailto:lenartlola@proton.me"
