name: Zola on GitHub Pages

on:
  push:
    branches:
      - zola
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout zola branch
        uses: actions/checkout@v4
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          PAGES_BRANCH: zola
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_FLAGS: ""

